name: rate_review
description: A new Flutter project.
publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  get: ^4.6.1
  get_storage: ^2.0.3
  http: ^0.13.4
#  flutter_inappwebview: ^5.3.2
  flutter_inappwebview: ^5.7.2+2
  intl: ^0.17.0
  cryptography: ^2.0.5
  percent_indicator: ^4.0.0
#  permission_handler: ^8.3.0
  permission_handler: ^10.2.0
  url_launcher: ^6.1.0
  share: ^2.0.4
#  firebase_core: ^1.10.6
#  firebase_messaging: ^11.2.11
#  flutter_local_notifications: ^12.0.4
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.3
  flutter_local_notifications: ^9.4.0
  #  firebase_analytics: ^9.1.0
  image_picker: ^0.8.4+7
  responsive_framework: ^0.1.5
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.13
  timeline_tile: ^2.0.0
  simple_tooltip: ^1.0.0
  flutter_email_sender: ^5.1.0
  shared_preferences_android: ^2.0.10
  shared_preferences_ios: ^2.0.9
  path_provider: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

#dependency_overrides:


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/svg/
    - assets/fonts/


  fonts:
    - family: gotham_light_regular
      fonts:
        - asset: assets/fonts/gotham_light_regular.otf
    - family: gothamnarrowbook
      fonts:
        - asset: assets/fonts/gothamnarrowbook.otf
    - family: gothamnarrowmedium
      fonts:
        - asset: assets/fonts/gothamnarrowmedium.otf
    - family: gothamnarrowbold
      fonts:
        - asset: assets/fonts/gothamnarrowbold.otf